services:
  frontend:
    build:
      context: "."
      dockerfile: "./container/dev.Dockerfile"
    container_name: "frontend"
    restart: "unless-stopped"
    environment:
      - "HOST=${FRONTEND_HOST}"
      - "PORT=${FRONTEND_PORT}"
      - "NUXT_BASE_URL=${BASE_URL}"
      - "NUXT_APP_BASE_URL=${API_BASE_URL}"
      - "NUXT_PUBLIC_BASE_URL=${BASE_URL}"
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - "./frontend:/srv/app"
